### ISSUE TITLE
No errors after loosing connection, internal buffering mechanism not working

### ISSUE THREAD

**Issue by trebacz626** [Kresten/winston-papertrail-transport#4]
Code:
```
import {Logger} from "winston";
import * as configService from "./config/ConfigService"

// eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
const winston = require('winston');

// eslint-disable-next-line @typescript-eslint/no-require-imports
require('winston-papertrail').Papertrail;

const logger = getTrueLogger();



function getTrueLogger(): Logger {
    const winstonPapertrail = new winston.transports.Papertrail({
        ...configService.papertrailHostAndPort(),
        program: `${configService.getAppVersion()}_${configService.getHashedUserMail()}`,

    });

    // eslint-disable-next-line @typescript-eslint/tslint/config
    winstonPapertrail.on('error', function (err): void {
        console.log("errryroro");
        if (configService.shouldDisplayPappertrailConnectionError()) {
            // eslint-disable-next-line no-console
            console.log(err);
        } else {
            // eslint-disable-next-line no-console
            console.log("log error");
        }
    });

    return new winston.createLogger({
        format: winston.format.combine(
            winston.format.timestamp(),
            winston.format.prettyPrint()
        ),
        transports: [winstonPapertrail],
        exceptionHandlers: [winstonPapertrail]
    });
}
async function run() {
    while (true) {
        logger.info(`Experiment: ${new Date()}`);
        await new Promise((resolve, reject) => setTimeout(resolve, 3000));
    }
}


run()
```

Some time ago I found out that my app stopped logging It turned out that it lost connection to papertrail without throwing any error.
I tested what happens when I turn off internet connection during logging and it turns out that no error is thrown. I even checked internal error handling mechanisms to see if they are triggered and it turned out that none of them is triggered. (I tested for an hour). I know that there is a buffer mechanism that preserves logs when a connection is lost and tries to upload them again x times and if it fails an error is thrown, but it is never triggered. I believe it is a problem with tls or sth like that.

What I would like to achieve is a way to know if we have lost connection and handle it in my app.

winston version 3.1.0

**Comment by Kresten** [comment]
You are using `require('winston-papertrail')`, which is not this package :)
But I will see if I can reproduce your issue.

**Comment by trebacz626** [comment]
Oh sorry I was trying both libraries here is a code with yours:

```
import {Logger} from "winston";
import * as configService from "./config/ConfigService"

// eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
const winston = require('winston');

// eslint-disable-next-line @typescript-eslint/no-require-imports
const Papertrail = require('winston-papertrail-transport').PapertrailTransport;

const logger = getTrueLogger();



function getTrueLogger(): Logger {
    const winstonPapertrail = new Papertrail({
        ...configService.papertrailHostAndPort(),
        program: `${configService.getAppVersion()}_${configService.getHashedUserMail()}`,

    });

    // eslint-disable-next-line @typescript-eslint/tslint/config
    winstonPapertrail.on('error', function (err): void {
        if (configService.shouldDisplayPappertrailConnectionError()) {
            // eslint-disable-next-line no-console
            console.log(err);
        } else {
            // eslint-disable-next-line no-console
            console.log("log error");
        }
    });

    return new winston.createLogger({
        format: winston.format.combine(
            winston.format.timestamp(),
            winston.format.prettyPrint()
        ),
        transports: [winstonPapertrail],
        exceptionHandlers: [winstonPapertrail]
    });
}
async function run() {
    while (true) {
        console.log(`Experiment: ${new Date()}`)
        logger.info(`Experiment: ${new Date()}`);
        await new Promise((resolve, reject) => setTimeout(resolve, 3000));
    }
}


run()
```

**Comment by trebacz626** [comment]
Did you manage to reproduce this issue?

**Comment by Kresten** [comment]
Yes I did 👍 
I cleaned up in the code, and found some pretty critical reconnection bugs. I published a new package with a fix. I am now able to connect to papertrail, disable ethernet, reenable, and the transport also reconnects (unless the disconnection went on for too long). Please let me know if you run into any other issues! :)

I also noticed you tried to receive errors on `winstonPapertrail` instead of `winstonPapertrail.connection`, so I added a part to the README about tapping in on 'error' and 'connect' events :)

**Comment by trebacz626** [comment]
Hello, thank you for your changes but they did not quite solve my issue. I changed the listener to the one that you suggested and did not get any errors. After further investigation (adding console log at beginning of each method in this module) I saw that after more or less 3 minutes after disconnecting from internet module stops logging to papertrail, but I still see console logs from while loop in my code snippet. Moreover, after this happens no method is being called in your module. (no console log is fired :( ) so there is not even a chance that sth will be added to the buffer. 
What I would like to achieve is some kind of reconnection procedure or at least an information from logging module that it does not work. For now, it just stops working without any information.

**Comment by Kresten** [comment]
I am not able to reproduce your issue. I tried with your experiment like this: 
```
const { createLogger } = require('winston');
const { PapertrailTransport } = require('winston-papertrail-transport');

const logger = getTrueLogger();

function getTrueLogger() {
    const pt = new PapertrailTransport({
        host: 'logs.papertrail.com',
        port: 12345,
        hostname: 'some:name',
    });

    pt.connection.on('error', (err) => {
        console.log(err);
    });

    return new createLogger({transports: [pt]});
}

async function run() {
    while (true) {
        console.log(`Experiment: ${new Date()}`)
        logger.info(`Experiment: ${new Date()}`);
        await new Promise((resolve, reject) => setTimeout(resolve, 3000));
    }
}

run()

```
I ran it, saw it started logging to papertrail, disabled my ethernet, received this error via `console.log()` in the listener:
```
Error: getaddrinfo ENOTFOUND logs.papertrail.com logs.papertrail.com:12345
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'logs.papertrail.com',
  host: 'logs6.papertrail.com',
  port: 12345}
```
I left my ethernet off for 4 minutes (`console.log()`s inbetween errors from `Experiment: Wed Sep 02 2020 10:30:29 GMT+0200 (Central European Summer Time)` to `Experiment: Wed Sep 02 2020 10:34:29 GMT+0200 (Central European Summer Time)`).
When I turned on ethernet again, errors in console stopped, and everything missing was sent to papertrail in correct order.

**Comment by trebacz626** [comment]
Do you use Windows or Linux? We tested it on 2 linux devices and it doesn't work on both of them (behawes as described above), and on 1 Windows device and there it works.

**Comment by trebacz626** [comment]
Update, on 1 linux device it started returning errors after 20 minutes

**Comment by Kresten** [comment]
I have only tested on Windows, I'll try on Linux when I get the time. But very strange!
